export const typeOptions = [
  'BUSINESS',
  'DESIGN',
  'EDUCATION',
  'ENGINEERING',
  'MARKETING',
  'HR_OPERATIONS',
  'PERSONAL',
  'PRODUCTIVITY',
  'PRODUCT_MANAGEMENT',
  'PROJECT_MANAGEMENT',
  'REMOTE_WORK',
  'SALES',
  'SUPPORT',
  'TEAM_MANAGEMENT'
]