import 'dotenv/config'

export const env = {
  MONGODB_URI: process.env.MONGODB_URI,
  DATABASE_NAME: process.env.DATABASE_NAME,

  LOCAL_DEV_APP_HOST: process.env.LOCAL_DEV_APP_HOST,
  LOCAL_DEV_APP_PORT: process.env.LOCAL_DEV_APP_PORT,

  BUILD_MODE: process.env.BUILD_MODE,

  AUTHOR: process.env.AUTHOR,

  WEBSITE_DOMAIN_DEVELOPMENT: process.env.WEBSITE_DOMAIN_DEVELOPMENT,
  WEBSITE_DOMAIN_PRODUCTION: process.env.WEBSITE_DOMAIN_PRODUCTION,
  CORS_ALLOWED_ORIGINS: process.env.CORS_ALLOWED_ORIGINS,

  EMAIL_USERNAME: process.env.EMAIL_USERNAME,
  EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,

  API_KEY_MAIL: process.env.API_KEY_MAIL,

  ACCESS_TOKEN_SECRET_SIGNATURE: process.env.ACCESS_TOKEN_SECRET_SIGNATURE,
  ACCESS_TOKEN_LIFE: process.env.ACCESS_TOKEN_LIFE,
  AI_TOKEN_LIFE: process.env.AI_TOKEN_LIFE || '15m',

  REFRESH_TOKEN_SECRET_SIGNATURE: process.env.REFRESH_TOKEN_SECRET_SIGNATURE,
  REFRESH_TOKEN_LIFE: process.env.REFRESH_TOKEN_LIFE,

  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,

  REDIS_CACHE_HOST: process.env.REDIS_CACHE_HOST,
  REDIS_CACHE_PORT: process.env.REDIS_CACHE_PORT,
  REDIS_CACHE_PASSWORD: process.env.REDIS_CACHE_PASSWORD,

  REDIS_REALTIME_HOST: process.env.REDIS_REALTIME_HOST,
  REDIS_REALTIME_PORT: process.env.REDIS_REALTIME_PORT,
  REDIS_REALTIME_PASSWORD: process.env.REDIS_REALTIME_PASSWORD,

  // S3 credential
  AWS_REGION: process.env.AWS_REGION,
  AWS_S3_BUCKET: process.env.AWS_S3_BUCKET,
  AWS_CLOUDFRONT_DOMAIN: process.env.AWS_CLOUDFRONT_DOMAIN,

  // Bedrock AI
  BEDROCK_AWS_ACCESS_KEY_ID: process.env.BEDROCK_AWS_ACCESS_KEY_ID,
  BEDROCK_AWS_SECRET_ACCESS_KEY: process.env.BEDROCK_AWS_SECRET_ACCESS_KEY,
  BEDROCK_REGION: process.env.BEDROCK_REGION || 'us-east-1',

  // Shared EFS storage mounted on backend EC2 instances
  EFS_EXPORT_ROOT: process.env.EFS_EXPORT_ROOT || '/mnt/taskio-shared/exports'
}
